name: 11

on:
  #release:
  #  types: published
 # schedule:
  #  - cron: 20 0/1 * * * 
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  New-Update-Files:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        echo "start=$(date +%s)" >> $GITHUB_ENV
   
    
    - name: Total time
      run: |
         end=$(date +%s)
         seconds=$(( end - start ))
         hour=$(( $seconds/3600 ))
         min=$(( ($seconds-${hour}*3600)/60 ))
         sec=$(( $seconds-${hour}*3600-${min}*60 ))
         HMS=`echo ${hour}:${min}:${sec}`
         echo $HMS
         echo $seconds
         echo $start
         echo $end
         echo "time1=$HMS" >> $GITHUB_ENV
             
    - name: Telegram notification upload success
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
           ҉ 🎡同步成功 ҉
           编译耗时：${{ env.time }}时${{ env.time1 }}分
