name: Delete Artifacts Update Checker

on:
  #release:
  #  types: published
 # schedule:
  #  - cron: 20 0/1 * * * 
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  New-Update-Files:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        pwd
        rm -rf ./backup/kernel
        mkdir -p ./backup/kernel
        svn export https://github.com/ophub/kernel/trunk/pub/stable ./backup/kernel --force
        rm -rf ./backup/kernel/5.10.*
        rm -rf ./backup/kernel/5.4.*
        starttime=`date +'%Y-%m-%d %H:%M:%S'`
    - name: Download kernel
      uses: robinraju/release-downloader@v1.3
      with:
        repository: "Jejz168/compile-kernel"
        latest: true
        fileName: "*"
        tarBall: true
        out-file-path: ./backup/kernel

    - name: Release tar
      run: |
        cd ./backup/kernel
        find ./ -name *ophub*|xargs rm -rf
        find ./ -name *compile*|xargs rm -rf
        ls ./*.tar.gz |xargs -n1 tar xzvf
        rm -rf ./*gz
        
    - name: Commit
      run: |
        git config --global user.email 349589369@qq.com
        git config --global user.name Jejz-OpenWrt
        git add .
        git commit -m"action:`date`"
        git pull --rebase
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        
    - name: Total time
      run: |
         endtime=`date +'%Y-%m-%d %H:%M:%S'`
         start_seconds=$(date --date="$starttime" +%s);
         end_seconds=$(date --date="$endtime" +%s);
         time=$(( end_seconds-start_seconds ))
         echo "$time"
         time1=$time/60
         echo "$time1"
         echo "time2=$time1" >> $GITHUB_ENV
             
    - name: Telegram notification upload success
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
           ҉ 🎡同步成功 ҉
           编译耗时：${{ env.time2 }}时${{ env.time1 }}分
